import styles from '../styles/Dash.module.css'
import Head from 'next/head'
import Navbar_top from '../src/navbar_top'

function Dashboard() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Universe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar_top/>
            <div className={styles.body_container}>
                <div className={styles.navbar}>

                </div>
            </div>
        </div>
    )
}

export default Dashboard