import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Universe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card_login}>
          <div className={styles.logo}>
            <h1 className={styles.logo_title}>Universe</h1>
            <Image src="/saturn.png" alt="Logo" width={40} height={40} />
          </div>
          <h2 className={styles.title_login}>Bem vindos !</h2>
          <div className={styles.textbox}>
            <h2 className={styles.title_textbox}>Preencha os dados do login para acessar</h2>
            <div className={styles.login}>
              <label className={styles.input_title}>Usuário</label>
              <input className={styles.input_login}></input>
            </div>
            <div className={styles.login}>
              <label>Senha</label>
              <input className={styles.input_login}></input>
            </div>
            <div className={styles.button}>
            <Link href="/dashboard">
              <a className={styles.card}>
                Entrar
              </a>
            </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
